<a href="https://colab.research.google.com/github/mahasvinreddy07/ML_Lab/blob/main/Numpy_AP23110010075.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Numpy-3")


Welcome to Numpy-3


In [ ]:

import numpy as np

In [ ]:
a = np.array([0, 1, 2])
print(type(a))
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])
# Change an element of the array
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
df.shape

(96, 7)

In [ ]:
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
import pandas as pd
import io

data = """date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg
06-10-2017,5464,200,181,5,0,66
07-10-2017,6041,100,197,8,0,66
08-10-2017,25,100,0,5,0,66
09-10-2017,5461,100,174,4,0,66
10-10-2017,6915,200,223,5,500,66
11-10-2017,4545,100,149,6,0,66
12-10-2017,4340,100,140,6,0,66
13-10-2017,1230,100,38,7,0,66
14-10-2017,61,100,1,5,0,66
15-10-2017,1258,100,40,6,0,65
16-10-2017,3148,100,101,8,0,65
17-10-2017,4687,100,152,5,0,65
18-10-2017,4732,300,150,6,500,65
19-10-2017,3519,100,113,7,0,65
20-10-2017,1580,100,49,5,0,65
21-10-2017,2822,100,86,6,0,65
22-10-2017,181,100,6,8,0,65
23-10-2017,3158,200,99,5,0,65
24-10-2017,4383,200,143,4,0,64
25-10-2017,3881,200,125,5,0,64
26-10-2017,4037,200,129,6,0,64
27-10-2017,202,200,6,8,0,64
28-10-2017,292,200,9,5,0,64
29-10-2017,330,300,10,6,0,64
30-10-2017,2209,200,72,5,0,64
31-10-2017,4550,300,150,8,500,64
01-11-2017,4435,300,141,5,0,64
02-11-2017,4779,300,156,4,0,64
03-11-2017,1831,300,57,5,0,64
04-11-2017,2255,300,72,4,0,64
05-11-2017,539,300,17,5,500,64
06-11-2017,5464,300,181,4,0,64
07-11-2017,6041,200,197,3,0,64
08-11-2017,4068,300,131,2,0,64
09-11-2017,4683,300,154,9,0,64
10-11-2017,4033,300,137,5,0,64
11-11-2017,6314,300,193,6,500,64
12-11-2017,614,300,19,4,500,64
13-11-2017,3149,300,101,5,500,64
14-11-2017,4005,300,139,8,500,64
15-11-2017,4880,300,164,4,500,64
16-11-2017,4136,300,137,5,500,64
17-11-2017,705,300,22,6,500,64
18-11-2017,570,200,17,5,500,64
19-11-2017,269,300,9,6,500,64
20-11-2017,4275,300,145,5,0,64
21-11-2017,5999,300,192,6,0,64
22-11-2017,4421,300,146,5,0,64
23-11-2017,6930,300,234,6,0,64
24-11-2017,5195,300,167,5,0,64
25-11-2017,546,300,16,6,0,64
26-11-2017,493,300,17,7,500,64
27-11-2017,995,300,32,6,500,64
28-11-2017,1163,200,35,7,500,64
29-11-2017,6676,100,220,6,500,64
30-11-2017,3608,300,116,5,500,64
01-12-2017,774,300,23,6,500,64
02-12-2017,1421,300,44,7,500,64
03-12-2017,4064,300,131,8,500,64
04-12-2017,2725,300,86,8,500,64
05-12-2017,5934,300,194,7,500,64
06-12-2017,1867,300,60,8,500,64
07-12-2017,3721,100,121,5,500,64
08-12-2017,2374,200,76,4,0,64
09-12-2017,2909,200,93,3,500,64
10-12-2017,1648,100,53,3,500,64
11-12-2017,799,100,25,4,0,64
12-12-2017,7102,200,227,5,500,64
13-12-2017,3941,200,125,5,500,64
14-12-2017,7422,300,243,5,500,64
15-12-2017,437,200,14,3,500,64
16-12-2017,1231,200,39,4,500,64
17-12-2017,1696,100,55,4,0,64
18-12-2017,4921,200,158,5,500,64
19-12-2017,221,100,7,5,500,64
20-12-2017,6500,200,213,5,500,64
21-12-2017,3575,200,116,5,500,64
22-12-2017,4061,100,129,5,0,64
23-12-2017,651,100,21,5,0,64
24-12-2017,753,100,28,4,0,64
25-12-2017,518,100,16,3,0,64
26-12-2017,5537,300,180,4,500,64
27-12-2017,4108,200,138,5,500,64
28-12-2017,5376,300,176,5,500,64
29-12-2017,3066,200,99,4,500,64
30-12-2017,177,100,5,5,0,64
31-12-2017,36,100,1,3,0,64
01-01-2018,299,100,10,3,0,64
02-01-2018,1447,200,47,3,0,64
03-01-2018,2599,200,84,2,0,64
04-01-2018,702,100,23,3,0,64
05-01-2018,133,100,4,2,0,64
06-01-2018,153,300,0,8,0,64
07-01-2018,500,200,0,5,500,64
08-01-2018,2127,200,0,5,0,64
09-01-2018,2203,300,0,5,500,64
"""

df = pd.read_csv(io.StringIO(data))
df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')

display(df.head())

date  step_count  mood  calories_burned  hours_of_sleep  \
0 2017-10-06        5464   200              181               5   
1 2017-10-07        6041   100              197               8   
2 2017-10-08          25   100                0               5   
3 2017-10-09        5461   100              174               4   
4 2017-10-10        6915   200              223               5   

   bool_of_active  weight_kg  
0               0         66  
1               0         66  
2               0         66  
3               0         66  
4             500         66

from matplotlib import pyplot as plt
_df_16['step_count'].plot(kind='hist', bins=20, title='step_count')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17['mood'].plot(kind='hist', bins=20, title='mood')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_18['calories_burned'].plot(kind='hist', bins=20, title='calories_burned')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_19['hours_of_sleep'].plot(kind='hist', bins=20, title='hours_of_sleep')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_20.plot(kind='scatter', x='step_count', y='mood', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_21.plot(kind='scatter', x='mood', y='calories_burned', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_22.plot(kind='scatter', x='calories_burned', y='hours_of_sleep', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_23.plot(kind='scatter', x='hours_of_sleep', y='bool_of_active', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['step_count']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_24.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('step_count')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['mood']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_25.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('mood')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['calories_burned']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_26.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('calories_burned')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['hours_of_sleep']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_27.sort_values('date', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('hours_of_sleep')

from matplotlib import pyplot as plt
_df_28['step_count'].plot(kind='line', figsize=(8, 4), title='step_count')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_29['mood'].plot(kind='line', figsize=(8, 4), title='mood')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_30['calories_burned'].plot(kind='line', figsize=(8, 4), title='calories_burned')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_31['hours_of_sleep'].plot(kind='line', figsize=(8, 4), title='hours_of_sleep')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:

data[:44]

'date,step_count,mood,calories_burned,hours_o'

In [ ]:
data[0]

'd'

In [ ]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [ ]:
x = np.array([0, 1])
y = np.array([2.0, 3.0])
# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [ ]:
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
a = np.array([1, 2, 5, 3])
# add 1 to every element
print ("Adding 1 to every element:", a+1)
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
# square each element
print ("Squaring each element:", a**2)
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
